# Generated by Django 5.1.6 on 2025-02-23 14:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Payment Method Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=255, verbose_name='Card Holder Name')),
                ('last_four', models.CharField(max_length=4, verbose_name='Last 4 Digits')),
                ('encrypted_card_number', models.CharField(blank=True, max_length=255)),
                ('expiry_month', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Expiry Month')),
                ('expiry_year', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Expiry Year')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='payments.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.savedcard')),
            ],
        ),
    ]
