# Generated by Django 5.1.6 on 2025-02-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcard',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='payments.paymentmethod'),
        ),
    ]
