import decimal
from django.core.management.base import BaseCommand
from listings.models import (
    Hotel,
    Room,
    Restaurant,
    MenuItem,
    CarRentalAgency,
    Car,
)


class Command(BaseCommand):
    help = "Fill the database with sample hotels, rooms, restaurants, menu items, car rental agencies, and cars."

    def handle(self, *args, **options):
        self.stdout.write("Filling Hotels and Rooms...")

        hotels_data = [
            {
                "name": "فندق الأفق الذهبي",
                "address": "الجزائر العاصمة، الجزائر",
                "description": "فندق فاخر يقع في مرتفعات الجزائر العاصمة، يوفر إطلالات خلابة على المدينة والبحر، ويبعد 10 دقائق عن مقر مجلس الأمة.",
                "rating": decimal.Decimal("5.0"),
                "price_per_night": decimal.Decimal("15000"),
                "has_wifi": True,
                "has_parking": True,
                "has_swimming_pool": True,
                "has_gym": True,
                "has_restaurant": True,
                "has_24hr_reception": True,
                "has_non_smoking_rooms": True,
                "main_image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "rooms": [
                    {
                        "room_type": "single",
                        "room_number": "101",
                        "floor": 1,
                        "capacity": 1,
                        "price_per_night": decimal.Decimal("7000"),
                        "size_sqm": 20,
                        "is_available": True,
                        "has_air_conditioning": False,
                        "has_heating": False,
                        "has_minibar": False,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مفردة في فندق الأفق الذهبي.",
                    },
                    {
                        "room_type": "double",
                        "room_number": "102",
                        "floor": 1,
                        "capacity": 2,
                        "price_per_night": decimal.Decimal("12000"),
                        "size_sqm": 25,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": False,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مزدوجة في فندق الأفق الذهبي.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "201",
                        "floor": 2,
                        "capacity": 3,
                        "price_per_night": decimal.Decimal("18000"),
                        "size_sqm": 35,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح صغير في فندق الأفق الذهبي.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "301",
                        "floor": 3,
                        "capacity": 4,
                        "price_per_night": decimal.Decimal("25000"),
                        "size_sqm": 50,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": True,
                        "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح فاخر في فندق الأفق الذهبي.",
                    },
                ],
            },
            {
                "name": "فندق الواحة الزرقاء",
                "address": "شارع فرانتز فانون، الجزائر العاصمة، الجزائر",
                "description": "فندق تاريخي يقع في وسط الجزائر العاصمة، يتميز بحدائقه الجميلة وخدماته الفاخرة، ويبعد 15 دقيقة عن مقر مجلس الأمة.",
                "rating": decimal.Decimal("4.0"),
                "price_per_night": decimal.Decimal("12000"),
                "has_wifi": True,
                "has_parking": True,
                "has_swimming_pool": True,
                "has_gym": False,
                "has_restaurant": True,
                "has_24hr_reception": True,
                "has_non_smoking_rooms": False,
                "main_image": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "rooms": [
                    {
                        "room_type": "single",
                        "room_number": "110",
                        "floor": 1,
                        "capacity": 1,
                        "price_per_night": decimal.Decimal("7500"),
                        "size_sqm": 22,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": False,
                        "has_minibar": False,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1631049035182-249067d7618e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مفردة في فندق الواحة الزرقاء.",
                    },
                    {
                        "room_type": "double",
                        "room_number": "120",
                        "floor": 2,
                        "capacity": 2,
                        "price_per_night": decimal.Decimal("13000"),
                        "size_sqm": 27,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مزدوجة في فندق الواحة الزرقاء.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "210",
                        "floor": 2,
                        "capacity": 3,
                        "price_per_night": decimal.Decimal("19000"),
                        "size_sqm": 40,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1568495248636-6432b97bd949?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح صغير في فندق الواحة الزرقاء.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "310",
                        "floor": 3,
                        "capacity": 4,
                        "price_per_night": decimal.Decimal("26000"),
                        "size_sqm": 55,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": True,
                        "image": "https://images.unsplash.com/photo-1594130139005-3f0c0f0e7c5e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح فاخر في فندق الواحة الزرقاء.",
                    },
                ],
            },
            {
                "name": "فندق النسيم الملكي",
                "address": "الجزائر العاصمة، الجزائر",
                "description": "فندق حديث وفاخر بتصميم عصري، يوفر إطلالات رائعة على البحر الأبيض المتوسط، مناسب للسياح ورجال الأعمال.",
                "rating": decimal.Decimal("5.0"),
                "price_per_night": decimal.Decimal("18000"),
                "has_wifi": True,
                "has_parking": True,
                "has_swimming_pool": True,
                "has_gym": True,
                "has_restaurant": True,
                "has_24hr_reception": True,
                "has_non_smoking_rooms": True,
                "main_image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "rooms": [
                    {
                        "room_type": "single",
                        "room_number": "201",
                        "floor": 2,
                        "capacity": 1,
                        "price_per_night": decimal.Decimal("8000"),
                        "size_sqm": 23,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": False,
                        "has_minibar": False,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1618773928121-c32242e63f39?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مفردة في فندق النسيم الملكي.",
                    },
                    {
                        "room_type": "double",
                        "room_number": "202",
                        "floor": 2,
                        "capacity": 2,
                        "price_per_night": decimal.Decimal("14000"),
                        "size_sqm": 28,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1621293954908-907159247fc8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مزدوجة في فندق النسيم الملكي.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "301",
                        "floor": 3,
                        "capacity": 3,
                        "price_per_night": decimal.Decimal("20000"),
                        "size_sqm": 42,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح صغير في فندق النسيم الملكي.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "401",
                        "floor": 4,
                        "capacity": 4,
                        "price_per_night": decimal.Decimal("28000"),
                        "size_sqm": 60,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": True,
                        "image": "https://images.unsplash.com/photo-1587985064135-0366536eab42?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح فاخر في فندق النسيم الملكي.",
                    },
                ],
            },
            {
                "name": "فندق اللؤلؤة البيضاء",
                "address": "الدار البيضاء، الجزائر العاصمة، الجزائر",
                "description": "فندق يقع بالقرب من مطار الجزائر الدولي، يوفر خدمات راقية للمسافرين، مع غرف مريحة ومرافق متكاملة.",
                "rating": decimal.Decimal("4.0"),
                "price_per_night": decimal.Decimal("13000"),
                "has_wifi": True,
                "has_parking": True,
                "has_swimming_pool": False,
                "has_gym": False,
                "has_restaurant": True,
                "has_24hr_reception": True,
                "has_non_smoking_rooms": True,
                "main_image": "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "rooms": [
                    {
                        "room_type": "single",
                        "room_number": "101",
                        "floor": 1,
                        "capacity": 1,
                        "price_per_night": decimal.Decimal("7500"),
                        "size_sqm": 22,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": False,
                        "has_minibar": False,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1566665797739-1674de7a421a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مفردة في فندق اللؤلؤة البيضاء.",
                    },
                    {
                        "room_type": "double",
                        "room_number": "102",
                        "floor": 1,
                        "capacity": 2,
                        "price_per_night": decimal.Decimal("13500"),
                        "size_sqm": 30,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": False,
                        "has_private_bathroom": True,
                        "has_sea_view": False,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1540518614846-7eded433c457?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "غرفة مزدوجة في فندق اللؤلؤة البيضاء.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "201",
                        "floor": 2,
                        "capacity": 3,
                        "price_per_night": decimal.Decimal("21000"),
                        "size_sqm": 45,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": False,
                        "image": "https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح صغير في فندق اللؤلؤة البيضاء.",
                    },
                    {
                        "room_type": "suite",
                        "room_number": "301",
                        "floor": 3,
                        "capacity": 4,
                        "price_per_night": decimal.Decimal("29000"),
                        "size_sqm": 65,
                        "is_available": True,
                        "has_air_conditioning": True,
                        "has_heating": True,
                        "has_minibar": True,
                        "has_tv": True,
                        "has_safe": True,
                        "has_private_bathroom": True,
                        "has_sea_view": True,
                        "has_balcony": True,
                        "image": "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                        "description": "جناح فاخر في فندق اللؤلؤة البيضاء.",
                    },
                ],
            },
        ]

        for hotel_info in hotels_data:
            hotel, created = Hotel.objects.get_or_create(
                name=hotel_info["name"],
                defaults={
                    "address": hotel_info["address"],
                    "description": hotel_info["description"],
                    "rating": hotel_info["rating"],
                    "price_per_night": hotel_info["price_per_night"],
                    "has_wifi": hotel_info.get("has_wifi", False),
                    "has_parking": hotel_info.get("has_parking", False),
                    "has_swimming_pool": hotel_info.get("has_swimming_pool", False),
                    "has_gym": hotel_info.get("has_gym", False),
                    "has_restaurant": hotel_info.get("has_restaurant", False),
                    "has_24hr_reception": hotel_info.get("has_24hr_reception", False),
                    "has_non_smoking_rooms": hotel_info.get(
                        "has_non_smoking_rooms", False
                    ),
                    "main_image": hotel_info.get("main_image", "hotel.png"),
                },
            )
            for room_info in hotel_info.get("rooms", []):
                Room.objects.get_or_create(
                    hotel=hotel,
                    room_number=room_info["room_number"],
                    defaults={
                        "room_type": room_info["room_type"],
                        "floor": room_info["floor"],
                        "capacity": room_info["capacity"],
                        "price_per_night": room_info["price_per_night"],
                        "size_sqm": room_info["size_sqm"],
                        "is_available": room_info.get("is_available", True),
                        "has_air_conditioning": room_info.get(
                            "has_air_conditioning", False
                        ),
                        "has_heating": room_info.get("has_heating", False),
                        "has_minibar": room_info.get("has_minibar", False),
                        "has_tv": room_info.get("has_tv", False),
                        "has_safe": room_info.get("has_safe", False),
                        "has_private_bathroom": room_info.get(
                            "has_private_bathroom", True
                        ),
                        "has_sea_view": room_info.get("has_sea_view", False),
                        "has_balcony": room_info.get("has_balcony", False),
                        "image": room_info.get("image", "room.png"),
                        "description": room_info.get("description", ""),
                    },
                )
        self.stdout.write("Hotels and Rooms added.")

        self.stdout.write("Filling Restaurants and Menu Items...")

        restaurants_data = [
            {
                "name": "مطعم الأندلس",
                "address": "شارع الاستقلال، الجزائر العاصمة، الجزائر",
                "description": "مطعم فاخر يقدم الأطباق التقليدية الجزائرية بلمسة عصرية، مع أجواء شرقية هادئة.",
                "rating": decimal.Decimal("5.0"),
                "price_range": decimal.Decimal("300"),
                "has_family_tables": True,
                "has_business_tables": False,
                "has_private_tables": True,
                "has_hot_dishes": True,
                "has_cold_dishes": False,
                "has_desserts": True,
                "has_beverages": True,
                "has_salads": True,
                "main_image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "menu_items": [
                    {
                        "name": "كسكسي ملكي",
                        "category": "main",
                        "description": "طبق تقليدي يحتوي على الكسكسي المطهو بالبخار مع لحم الضأن والخضروات المشكلة.",
                        "price": decimal.Decimal("1500"),
                        "is_available": True,
                        "preparation_time": 30,
                        "spiciness_level": 2,
                        "image": "https://images.unsplash.com/photo-1585937421612-70a008356570?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "شوربة فريك",
                        "category": "appetizer",
                        "description": "حساء تقليدي من القمح المهروس مع الدجاج والبهارات الجزائرية.",
                        "price": decimal.Decimal("700"),
                        "is_available": True,
                        "preparation_time": 20,
                        "spiciness_level": 1,
                        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "قلب اللوز",
                        "category": "dessert",
                        "description": "حلوى جزائرية مشهورة مكونة من السميد والعسل واللوز المحمص.",
                        "price": decimal.Decimal("500"),
                        "is_available": True,
                        "preparation_time": 15,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "عصير الليمون بالنعناع",
                        "category": "beverage",
                        "description": "عصير طبيعي منعش من الليمون الطازج والنعناع.",
                        "price": decimal.Decimal("400"),
                        "is_available": True,
                        "preparation_time": 5,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
            {
                "name": "لو باتيو",
                "address": "حي راقي، وهران، الجزائر",
                "description": "مطعم أنيق يقدم المأكولات المتوسطية والفرنسية بلمسة إبداعية.",
                "rating": decimal.Decimal("4.0"),
                "price_range": decimal.Decimal("400"),
                "has_family_tables": False,
                "has_business_tables": True,
                "has_private_tables": True,
                "has_hot_dishes": True,
                "has_cold_dishes": True,
                "has_desserts": True,
                "has_beverages": True,
                "has_salads": False,
                "main_image": "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "menu_items": [
                    {
                        "name": "ستيك بالفلفل الأسود",
                        "category": "main",
                        "description": "لحم بقري مشوي يقدم مع صلصة الفلفل الأسود والخضار المشوية.",
                        "price": decimal.Decimal("2800"),
                        "is_available": True,
                        "preparation_time": 35,
                        "spiciness_level": 2,
                        "image": "https://images.unsplash.com/photo-1600891964092-4316c288032e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "سلطة سيزر",
                        "category": "salad",
                        "description": "سلطة تقليدية بالدجاج المشوي، الخس، جبن البارميزان، وصلصة السيزر.",
                        "price": decimal.Decimal("1200"),
                        "is_available": True,
                        "preparation_time": 15,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "كريب بالنوتيلا",
                        "category": "dessert",
                        "description": "كريب فرنسي محشو بنوتيلا والبندق المقرمش.",
                        "price": decimal.Decimal("900"),
                        "is_available": True,
                        "preparation_time": 10,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1519676867240-f03562e64548?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "موهيتو فراولة",
                        "category": "beverage",
                        "description": "مشروب منعش بالفراولة والنعناع والليمون مع الصودا.",
                        "price": decimal.Decimal("600"),
                        "is_available": True,
                        "preparation_time": 7,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1546171753-97d7676e4602?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
            {
                "name": "دار القصبة",
                "address": "حي القصبة، الجزائر العاصمة، الجزائر",
                "description": "مطعم شعبي بطابع تقليدي يعكس التراث الجزائري.",
                "rating": decimal.Decimal("5.0"),
                "price_range": decimal.Decimal("200"),
                "has_family_tables": True,
                "has_business_tables": False,
                "has_private_tables": True,
                "has_hot_dishes": True,
                "has_cold_dishes": False,
                "has_desserts": True,
                "has_beverages": True,
                "has_salads": True,
                "main_image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "menu_items": [
                    {
                        "name": "شخشوخة",
                        "category": "main",
                        "description": "طبق تقليدي مصنوع من رقائق العجين مع المرق الحار والدجاج أو اللحم.",
                        "price": decimal.Decimal("1600"),
                        "is_available": True,
                        "preparation_time": 40,
                        "spiciness_level": 3,
                        "image": "https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "سلطة مشوية",
                        "category": "salad",
                        "description": "مزيج من الطماطم، الفلفل المشوي، الباذنجان مع زيت الزيتون والتوابل.",
                        "price": decimal.Decimal("800"),
                        "is_available": True,
                        "preparation_time": 15,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "مقروض",
                        "category": "dessert",
                        "description": "حلوى تقليدية مصنوعة من السميد، محشوة بالتمر، ومغمورة بالعسل.",
                        "price": decimal.Decimal("600"),
                        "is_available": True,
                        "preparation_time": 20,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1551879400-111a9087cd86?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "شاي بالنعناع",
                        "category": "beverage",
                        "description": "شاي أخضر مغربي بالنعناع الطازج.",
                        "price": decimal.Decimal("300"),
                        "is_available": True,
                        "preparation_time": 5,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
            {
                "name": "لو بلازا",
                "address": "وسط المدينة، قسنطينة، الجزائر",
                "description": "مطعم حديث يقدم مزيجًا من الأطباق العالمية والجزائرية في أجواء أنيقة.",
                "rating": decimal.Decimal("4.0"),
                "price_range": decimal.Decimal("500"),
                "has_family_tables": False,
                "has_business_tables": True,
                "has_private_tables": True,
                "has_hot_dishes": True,
                "has_cold_dishes": True,
                "has_desserts": True,
                "has_beverages": True,
                "has_salads": False,
                "main_image": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "menu_items": [
                    {
                        "name": "لازانيا باللحم",
                        "category": "main",
                        "description": "لازانيا إيطالية محشوة باللحم المفروم وصلصة الطماطم وجبن الموتزاريلا.",
                        "price": decimal.Decimal("2000"),
                        "is_available": True,
                        "preparation_time": 30,
                        "spiciness_level": 1,
                        "image": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "كولسلو",
                        "category": "salad",
                        "description": "سلطة كرمب طازجة مع الجزر والمايونيز والليمون.",
                        "price": decimal.Decimal("900"),
                        "is_available": True,
                        "preparation_time": 10,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1551248429-40975aa4de74?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "براوني بالشوكولاتة",
                        "category": "dessert",
                        "description": "قطعة براوني غنية بالشوكولاتة تقدم مع صوص الكراميل.",
                        "price": decimal.Decimal("1000"),
                        "is_available": True,
                        "preparation_time": 15,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "name": "قهوة تركية",
                        "category": "beverage",
                        "description": "قهوة محضرة على الطريقة التركية مع رغوة غنية.",
                        "price": decimal.Decimal("500"),
                        "is_available": True,
                        "preparation_time": 5,
                        "spiciness_level": 0,
                        "image": "https://images.unsplash.com/photo-157894333759-4d86bff0c3d0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
        ]

        for res_info in restaurants_data:
            restaurant, created = Restaurant.objects.get_or_create(
                name=res_info["name"],
                defaults={
                    "address": res_info["address"],
                    "description": res_info["description"],
                    "rating": res_info["rating"],
                    "price_range": res_info["price_range"],
                    "has_family_tables": res_info.get("has_family_tables", False),
                    "has_business_tables": res_info.get("has_business_tables", False),
                    "has_private_tables": res_info.get("has_private_tables", False),
                    "has_hot_dishes": res_info.get("has_hot_dishes", False),
                    "has_cold_dishes": res_info.get("has_cold_dishes", False),
                    "has_desserts": res_info.get("has_desserts", False),
                    "has_beverages": res_info.get("has_beverages", False),
                    "has_salads": res_info.get("has_salads", False),
                    "main_image": res_info.get("main_image", "restaurant.png"),
                },
            )
            for item in res_info.get("menu_items", []):
                MenuItem.objects.get_or_create(
                    restaurant=restaurant,
                    name=item["name"],
                    defaults={
                        "category": item["category"],
                        "description": item["description"],
                        "price": item["price"],
                        "is_available": item.get("is_available", True),
                        "preparation_time": item.get("preparation_time", 15),
                        "spiciness_level": item.get("spiciness_level", 0),
                        "image": item.get("image", "food.png"),
                    },
                )
        self.stdout.write("Restaurants and Menu Items added.")

        self.stdout.write("Filling Car Rental Agencies and Cars...")

        agencies_data = [
            {
                "name": "الجزائر لتأجير السيارات",
                "address": "وسط المدينة، الجزائر العاصمة، الجزائر",
                "description": "وكالة متخصصة في تأجير السيارات الفاخرة والاقتصادية بأسعار تنافسية.",
                "rating": decimal.Decimal("5.0"),
                "has_24hr_service": True,
                "has_driver_service": True,
                "has_airport_pickup": True,
                "has_long_term_rental": True,
                "has_short_term_rental": False,
                "has_full_insurance": True,
                "main_image": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "cars": [
                    {
                        "brand": "مرسيدس بنز",
                        "model": "C-Class",
                        "year": 2022,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("15000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1583121274602-3e2820c69888?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "تويوتا",
                        "model": "كورولا",
                        "year": 2021,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("8000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1590362891991-f776e747a588?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "هيونداي",
                        "model": "i10",
                        "year": 2020,
                        "transmission": "manual",
                        "price_per_day": decimal.Decimal("5000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "جيب",
                        "model": "شيروكي",
                        "year": 2023,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("18000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1604341329554-154d3d645974?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
            {
                "name": "وهران لتأجير السيارات",
                "address": "حي الأمير، وهران، الجزائر",
                "description": "وكالة توفر أحدث السيارات الاقتصادية والعائلية بأفضل الأسعار.",
                "rating": decimal.Decimal("4.0"),
                "has_24hr_service": False,
                "has_driver_service": False,
                "has_airport_pickup": True,
                "has_long_term_rental": False,
                "has_short_term_rental": True,
                "has_full_insurance": True,
                "main_image": "https://images.unsplash.com/photo-1594189397329-a035f1c3e500?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "cars": [
                    {
                        "brand": "بيجو",
                        "model": "208",
                        "year": 2021,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("7000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1605893477799-b99e3b4af741?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "كيا",
                        "model": "سبورتاج",
                        "year": 2022,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("12000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1617624085810-3df2165bd11b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "داسيا",
                        "model": "سانديرو",
                        "year": 2020,
                        "transmission": "manual",
                        "price_per_day": decimal.Decimal("6000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "رينو",
                        "model": "كليو 5",
                        "year": 2023,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("9000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1570733577524-3a047079e80d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
            {
                "name": "قسنطينة لتأجير السيارات",
                "address": "شارع الاستقلال، قسنطينة، الجزائر",
                "description": "وكالة توفر سيارات حديثة بمواصفات عالية مع خدمة توصيل إلى أي مكان.",
                "rating": decimal.Decimal("5.0"),
                "has_24hr_service": True,
                "has_driver_service": True,
                "has_airport_pickup": False,
                "has_long_term_rental": True,
                "has_short_term_rental": False,
                "has_full_insurance": True,
                "main_image": "https://images.unsplash.com/photo-1579740141769-3a250a86aa36?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "cars": [
                    {
                        "brand": "أودي",
                        "model": "A3",
                        "year": 2022,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("14000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "فورد",
                        "model": "فوكس",
                        "year": 2021,
                        "transmission": "manual",
                        "price_per_day": decimal.Decimal("8500"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1551830820-330a71b99659?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "نيسان",
                        "model": "قشقاي",
                        "year": 2022,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("11000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "هيونداي",
                        "model": "توسان",
                        "year": 2023,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("13000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1600861194942-f883de0dfe96?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
            {
                "name": "عنابة لتأجير السيارات",
                "address": "وسط المدينة، عنابة، الجزائر",
                "description": "وكالة متخصصة في تأجير السيارات الاقتصادية والفاخرة مع خدمة توصيل.",
                "rating": decimal.Decimal("4.0"),
                "has_24hr_service": False,
                "has_driver_service": False,
                "has_airport_pickup": True,
                "has_long_term_rental": True,
                "has_short_term_rental": True,
                "has_full_insurance": True,
                "main_image": "https://images.unsplash.com/photo-1581561462307-5cc9f9135bb5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
                "cars": [
                    {
                        "brand": "بي إم دبليو",
                        "model": "X5",
                        "year": 2023,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("20000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "فولكس فاجن",
                        "model": "جولف 7",
                        "year": 2021,
                        "transmission": "manual",
                        "price_per_day": decimal.Decimal("9000"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1594070319944-7c0cbebb6f58?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "شيفروليه",
                        "model": "كابتيفا",
                        "year": 2022,
                        "transmission": "auto",
                        "price_per_day": decimal.Decimal("11500"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                    {
                        "brand": "تويوتا",
                        "model": "ياريس",
                        "year": 2020,
                        "transmission": "manual",
                        "price_per_day": decimal.Decimal("7500"),
                        "is_available": True,
                        "image": "https://images.unsplash.com/photo-1549399542-7e8ee6529319?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
                    },
                ],
            },
        ]

        for agency_info in agencies_data:
            agency, created = CarRentalAgency.objects.get_or_create(
                name=agency_info["name"],
                defaults={
                    "address": agency_info["address"],
                    "description": agency_info["description"],
                    "rating": agency_info["rating"],
                    "has_24hr_service": agency_info.get("has_24hr_service", False),
                    "has_driver_service": agency_info.get("has_driver_service", False),
                    "has_airport_pickup": agency_info.get("has_airport_pickup", False),
                    "has_long_term_rental": agency_info.get(
                        "has_long_term_rental", False
                    ),
                    "has_short_term_rental": agency_info.get(
                        "has_short_term_rental", False
                    ),
                    "has_full_insurance": agency_info.get("has_full_insurance", False),
                    "main_image": agency_info.get("main_image", "agency.png"),
                },
            )
            for car_info in agency_info.get("cars", []):
                Car.objects.get_or_create(
                    agency=agency,
                    brand=car_info["brand"],
                    model=car_info["model"],
                    year=car_info["year"],
                    defaults={
                        "transmission": car_info["transmission"],
                        "price_per_day": car_info["price_per_day"],
                        "is_available": car_info.get("is_available", True),
                        "driver_cost_per_day": car_info.get("driver_cost_per_day", 0),
                        "with_driver": car_info.get("with_driver", False),
                        "image": car_info.get("image", "car.png"),
                    },
                )
        self.stdout.write(self.style.SUCCESS("Data successfully populated."))
