# Generated by Django 5.1.6 on 2025-02-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Agency Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating')),
                ('has_24hr_service', models.BooleanField(default=False, verbose_name='24/7 Service')),
                ('has_driver_service', models.BooleanField(default=False, verbose_name='Driver Service')),
                ('has_airport_pickup', models.BooleanField(default=False, verbose_name='Airport Pickup')),
                ('has_long_term_rental', models.BooleanField(default=False, verbose_name='Long Term Rental')),
                ('has_short_term_rental', models.BooleanField(default=False, verbose_name='Short Term Rental')),
                ('has_full_insurance', models.BooleanField(default=False, verbose_name='Full Insurance')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='agencies/main/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Car Rental Agency',
                'verbose_name_plural': 'Car Rental Agencies',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Night')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Private Parking')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Fitness Center')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
                ('has_24hr_reception', models.BooleanField(default=False, verbose_name='24/7 Reception')),
                ('has_non_smoking_rooms', models.BooleanField(default=False, verbose_name='Non-smoking Rooms')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotels/main/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Restaurant Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating')),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Range')),
                ('has_family_tables', models.BooleanField(default=False, verbose_name='Family Tables')),
                ('has_business_tables', models.BooleanField(default=False, verbose_name='Business Tables')),
                ('has_private_tables', models.BooleanField(default=False, verbose_name='Private Tables')),
                ('has_hot_dishes', models.BooleanField(default=False, verbose_name='Hot Dishes')),
                ('has_cold_dishes', models.BooleanField(default=False, verbose_name='Cold Dishes')),
                ('has_beverages', models.BooleanField(default=False, verbose_name='Beverages')),
                ('has_desserts', models.BooleanField(default=False, verbose_name='Desserts')),
                ('has_salads', models.BooleanField(default=False, verbose_name='Salads')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='restaurants/main/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='CarAgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agencies/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.carrentalagency')),
            ],
            options={
                'verbose_name': 'Agency Image',
                'verbose_name_plural': 'Agency Images',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('transmission', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10, verbose_name='Transmission')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Day')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Image')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='listings.carrentalagency')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Image',
                'verbose_name_plural': 'Restaurant Images',
            },
        ),
    ]
