# Generated by Django 5.1.6 on 2025-02-23 14:22

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Agency Name')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=2, verbose_name='Rating')),
                ('has_24hr_service', models.BooleanField(default=False, verbose_name='24/7 Service')),
                ('has_driver_service', models.BooleanField(default=False, verbose_name='Driver Service')),
                ('has_airport_pickup', models.BooleanField(default=False, verbose_name='Airport Pickup')),
                ('has_long_term_rental', models.BooleanField(default=False, verbose_name='Long Term Rental')),
                ('has_short_term_rental', models.BooleanField(default=False, verbose_name='Short Term Rental')),
                ('has_full_insurance', models.BooleanField(default=False, verbose_name='Full Insurance')),
                ('main_image', models.ImageField(blank=True, default='agency.png', null=True, upload_to='agencies/main/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Car Rental Agency',
                'verbose_name_plural': 'Car Rental Agencies',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=2, verbose_name='Rating')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Night')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Private Parking')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Fitness Center')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
                ('has_24hr_reception', models.BooleanField(default=False, verbose_name='24/7 Reception')),
                ('has_non_smoking_rooms', models.BooleanField(default=False, verbose_name='Non-smoking Rooms')),
                ('main_image', models.ImageField(blank=True, default='hotel.png', null=True, upload_to='hotels/main/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dish Name')),
                ('category', models.CharField(choices=[('main', 'Main Dish'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('salad', 'Salad')], max_length=20, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Gluten Free')),
                ('spiciness_level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Spiciness Level')),
                ('preparation_time', models.IntegerField(default=15, verbose_name='Preparation Time (minutes)')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Calories')),
                ('image', models.ImageField(blank=True, default='food.png', null=True, upload_to='menu_items/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Restaurant Name')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=2, verbose_name='Rating')),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Range')),
                ('has_family_tables', models.BooleanField(default=False, verbose_name='Family Tables')),
                ('has_business_tables', models.BooleanField(default=False, verbose_name='Business Tables')),
                ('has_private_tables', models.BooleanField(default=False, verbose_name='Private Tables')),
                ('has_hot_dishes', models.BooleanField(default=False, verbose_name='Hot Dishes')),
                ('has_cold_dishes', models.BooleanField(default=False, verbose_name='Cold Dishes')),
                ('has_beverages', models.BooleanField(default=False, verbose_name='Beverages')),
                ('has_desserts', models.BooleanField(default=False, verbose_name='Desserts')),
                ('has_salads', models.BooleanField(default=False, verbose_name='Salads')),
                ('main_image', models.ImageField(blank=True, default='restaurant.png', null=True, upload_to='restaurants/main/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='CarAgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='agency.png', upload_to='agencies/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.carrentalagency')),
            ],
            options={
                'verbose_name': 'Agency Image',
                'verbose_name_plural': 'Agency Images',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('transmission', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10, verbose_name='Transmission')),
                ('driver_cost_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تسعيرة الركوب مع سائق')),
                ('with_driver', models.BooleanField(default=False, verbose_name='مع سائق')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Day')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(blank=True, default='car.png', null=True, upload_to='cars/', verbose_name='Image')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='listings.carrentalagency')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('car_brand', models.CharField(max_length=100, verbose_name='Car Brand')),
                ('car_type', models.CharField(max_length=100)),
                ('with_driver', models.BooleanField(default=False)),
                ('insurance_type', models.CharField(choices=[('basic', 'Basic'), ('full', 'Full Coverage')], max_length=50)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_agency_reservations', to='listings.carrentalagency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Reservation',
                'verbose_name_plural': 'Car Reservations',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='hotel.png', upload_to='hotels/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
            },
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_outdoor_area', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='listings.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Reservation',
                'verbose_name_plural': 'Hotel Reservations',
            },
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='food.png', upload_to='menu_items/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Image',
                'verbose_name_plural': 'Menu Item Images',
            },
        ),
        migrations.CreateModel(
            name='ReservationCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.car')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.carreservation')),
            ],
            options={
                'unique_together': {('reservation', 'car')},
            },
        ),
        migrations.AddField(
            model_name='carreservation',
            name='cars',
            field=models.ManyToManyField(related_name='car_reservations', through='listings.ReservationCar', to='listings.car'),
        ),
        migrations.CreateModel(
            name='ReservationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='listings.restaurant'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, default='restaurant.png', max_length=255, verbose_name='Caption')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Image',
                'verbose_name_plural': 'Restaurant Images',
            },
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('table_type', models.CharField(max_length=50, verbose_name='Table Type')),
                ('menu_items', models.ManyToManyField(related_name='menuitems_reservations', through='listings.ReservationMenuItem', to='listings.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_reservations', to='listings.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Reservation',
                'verbose_name_plural': 'Restaurant Reservations',
            },
        ),
        migrations.AddField(
            model_name='reservationmenuitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.restaurantreservation'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family'), ('deluxe', 'Deluxe')], max_length=20, verbose_name='Room Type')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room Number')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Night')),
                ('size_sqm', models.IntegerField(verbose_name='Size (m²)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('has_heating', models.BooleanField(default=False, verbose_name='Heating')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Minibar')),
                ('has_tv', models.BooleanField(default=False, verbose_name='TV')),
                ('has_safe', models.BooleanField(default=False, verbose_name='Safe')),
                ('has_private_bathroom', models.BooleanField(default=True, verbose_name='Private Bathroom')),
                ('has_sea_view', models.BooleanField(default=False, verbose_name='Sea View')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcony')),
                ('image', models.ImageField(blank=True, default='room.png', null=True, upload_to='rooms/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='listings.hotel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'unique_together': {('hotel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.hotelreservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.room')),
            ],
            options={
                'unique_together': {('reservation', 'room')},
            },
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='rooms',
            field=models.ManyToManyField(related_name='room_reservations', through='listings.ReservationRoom', to='listings.room'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='room.png', upload_to='rooms/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reservationmenuitem',
            unique_together={('reservation', 'menu_item')},
        ),
    ]
