# Generated by Django 5.1.6 on 2025-02-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_agency_reservations', to='listings.carrentalagency'),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='car_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='cars',
            field=models.ManyToManyField(related_name='car_reservations', through='listings.ReservationCar', to='listings.car'),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='insurance_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('full', 'Full Coverage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='with_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='has_outdoor_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='has_swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='listings.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='rooms',
            field=models.ManyToManyField(related_name='room_reservations', through='listings.ReservationRoom', to='listings.room'),
        ),
        migrations.AlterField(
            model_name='reservationcar',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservationroom',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='menu_items',
            field=models.ManyToManyField(related_name='menuitems_reservations', through='listings.ReservationMenuItem', to='listings.menuitem'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='reservation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='reservation_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_reservations', to='listings.restaurant'),
        ),
    ]
