# Generated by Django 5.1.6 on 2025-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_carreservation_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver_cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تسعيرة الركوب مع سائق'),
        ),
        migrations.AddField(
            model_name='car',
            name='with_driver',
            field=models.BooleanField(default=False, verbose_name='مع سائق'),
        ),
    ]
