# Generated by Django 5.1.6 on 2025-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_carrentalagency_rating_alter_hotel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='car.png', null=True, upload_to='cars/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='caragencyimage',
            name='image',
            field=models.ImageField(default='agency.png', upload_to='agencies/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='carrentalagency',
            name='main_image',
            field=models.ImageField(blank=True, default='agency.png', null=True, upload_to='agencies/main/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(blank=True, default='hotel.png', null=True, upload_to='hotels/main/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(default='hotel.png', upload_to='hotels/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='food.png', null=True, upload_to='menu_items/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='menuitemimage',
            name='image',
            field=models.ImageField(default='food.png', upload_to='menu_items/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, default='restaurant.png', null=True, upload_to='restaurants/main/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='caption',
            field=models.CharField(blank=True, default='restaurant.png', max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='room.png', null=True, upload_to='rooms/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default='room.png', upload_to='rooms/gallery/', verbose_name='Image'),
        ),
    ]
