# Generated by Django 5.1.6 on 2025-02-12 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_car_image_alter_caragencyimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Dish Name'),
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('car_brand', models.CharField(max_length=100, verbose_name='Car Brand')),
                ('car_type', models.CharField(max_length=100, verbose_name='Car Type')),
                ('with_driver', models.BooleanField(default=False, verbose_name='With Driver')),
                ('insurance_type', models.CharField(choices=[('basic', 'Basic'), ('full', 'Full Coverage')], max_length=50, verbose_name='Insurance Type')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.carrentalagency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Reservation',
                'verbose_name_plural': 'Car Reservations',
            },
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('check_in', models.DateField(verbose_name='Check-in Date')),
                ('check_out', models.DateField(verbose_name='Check-out Date')),
                ('number_of_guests', models.PositiveIntegerField(verbose_name='Number of Guests')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool Access')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Gym Access')),
                ('has_outdoor_area', models.BooleanField(default=False, verbose_name='Outdoor Area Access')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Reservation',
                'verbose_name_plural': 'Hotel Reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.car')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.carreservation')),
            ],
            options={
                'unique_together': {('reservation', 'car')},
            },
        ),
        migrations.AddField(
            model_name='carreservation',
            name='cars',
            field=models.ManyToManyField(related_name='reservations', through='listings.ReservationCar', to='listings.car'),
        ),
        migrations.CreateModel(
            name='ReservationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.hotelreservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.room')),
            ],
            options={
                'unique_together': {('reservation', 'room')},
            },
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='rooms',
            field=models.ManyToManyField(related_name='reservations', through='listings.ReservationRoom', to='listings.room'),
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('reservation_date', models.DateField(verbose_name='Reservation Date')),
                ('reservation_time', models.TimeField(verbose_name='Reservation Time')),
                ('table_type', models.CharField(max_length=50, verbose_name='Table Type')),
                ('menu_items', models.ManyToManyField(related_name='reservations', through='listings.ReservationMenuItem', to='listings.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Reservation',
                'verbose_name_plural': 'Restaurant Reservations',
            },
        ),
        migrations.AddField(
            model_name='reservationmenuitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.restaurantreservation'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationmenuitem',
            unique_together={('reservation', 'menu_item')},
        ),
    ]
