# Generated by Django 5.1.6 on 2025-02-23 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French')], default='ar', max_length=2, verbose_name='Language')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='DZD', max_length=3, verbose_name='Currency')),
                ('booking_notifications', models.BooleanField(default=True, verbose_name='Booking Notifications')),
                ('promotional_notifications', models.BooleanField(default=True, verbose_name='Promotional Notifications')),
                ('reminder_notifications', models.BooleanField(default=True, verbose_name='Reminder Notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
